// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: pod.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PodService_CreatePod_FullMethodName = "/pod.PodService/CreatePod"
	PodService_ExecInPod_FullMethodName = "/pod.PodService/ExecInPod"
)

// PodServiceClient is the client API for PodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodServiceClient interface {
	CreatePod(ctx context.Context, in *CreatePodRequest, opts ...grpc.CallOption) (*CreatePodResponse, error)
	ExecInPod(ctx context.Context, in *ExecInPodRequest, opts ...grpc.CallOption) (PodService_ExecInPodClient, error)
}

type podServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPodServiceClient(cc grpc.ClientConnInterface) PodServiceClient {
	return &podServiceClient{cc}
}

func (c *podServiceClient) CreatePod(ctx context.Context, in *CreatePodRequest, opts ...grpc.CallOption) (*CreatePodResponse, error) {
	out := new(CreatePodResponse)
	err := c.cc.Invoke(ctx, PodService_CreatePod_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podServiceClient) ExecInPod(ctx context.Context, in *ExecInPodRequest, opts ...grpc.CallOption) (PodService_ExecInPodClient, error) {
	stream, err := c.cc.NewStream(ctx, &PodService_ServiceDesc.Streams[0], PodService_ExecInPod_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &podServiceExecInPodClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PodService_ExecInPodClient interface {
	Recv() (*ExecInPodResponse, error)
	grpc.ClientStream
}

type podServiceExecInPodClient struct {
	grpc.ClientStream
}

func (x *podServiceExecInPodClient) Recv() (*ExecInPodResponse, error) {
	m := new(ExecInPodResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PodServiceServer is the server API for PodService service.
// All implementations must embed UnimplementedPodServiceServer
// for forward compatibility
type PodServiceServer interface {
	CreatePod(context.Context, *CreatePodRequest) (*CreatePodResponse, error)
	ExecInPod(*ExecInPodRequest, PodService_ExecInPodServer) error
	mustEmbedUnimplementedPodServiceServer()
}

// UnimplementedPodServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPodServiceServer struct {
}

func (UnimplementedPodServiceServer) CreatePod(context.Context, *CreatePodRequest) (*CreatePodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePod not implemented")
}
func (UnimplementedPodServiceServer) ExecInPod(*ExecInPodRequest, PodService_ExecInPodServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecInPod not implemented")
}
func (UnimplementedPodServiceServer) mustEmbedUnimplementedPodServiceServer() {}

// UnsafePodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodServiceServer will
// result in compilation errors.
type UnsafePodServiceServer interface {
	mustEmbedUnimplementedPodServiceServer()
}

func RegisterPodServiceServer(s grpc.ServiceRegistrar, srv PodServiceServer) {
	s.RegisterService(&PodService_ServiceDesc, srv)
}

func _PodService_CreatePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServiceServer).CreatePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodService_CreatePod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServiceServer).CreatePod(ctx, req.(*CreatePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodService_ExecInPod_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecInPodRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PodServiceServer).ExecInPod(m, &podServiceExecInPodServer{stream})
}

type PodService_ExecInPodServer interface {
	Send(*ExecInPodResponse) error
	grpc.ServerStream
}

type podServiceExecInPodServer struct {
	grpc.ServerStream
}

func (x *podServiceExecInPodServer) Send(m *ExecInPodResponse) error {
	return x.ServerStream.SendMsg(m)
}

// PodService_ServiceDesc is the grpc.ServiceDesc for PodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pod.PodService",
	HandlerType: (*PodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePod",
			Handler:    _PodService_CreatePod_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecInPod",
			Handler:       _PodService_ExecInPod_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pod.proto",
}
